apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nlqi5uot7-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nlqi5uot7-java-springboot-gitops